cannot-talk: '&7&cYou cannot talk until you have moved!'
reload-message: '&aPlugin reloaded!'
noPermissions: '&cYou do not have permission to use this command!'
spam-talk-message: '&ePlease &cdo not always write the same&e, it gets boring and leads to a &ckick.'
spam-whisper-message: '&ePlease &cdo not always whisper the same&e, it gets boring and leads to a &ckick.'
msg-diff-factor: 0.2
max-duplicates: 2
max-sentences-saved: 64
max-spam-saved: 32
min-message-length: 4
sentences-saved-per-player: 3
whitespace-frequency: 0.0625
not-moved-check-enabled: false
maximum-characters-per-minute: 300
maximum-unicode-ranges: 4
whisperCommands:
  - "tell"
  - "w"
  - "msg"
  - "whisper"
bots:
  - "6259c4b5-759f-4252-a6f7-d77818e125eb" # AnarchyB0T
  - "ddac1529-0729-4791-aa72-d82960ed8580" # moooomoooo
  - "f4e4573e-0bfa-4ae8-9f4c-c1d935e0b050" # Leeunderscore
  - "6a11762d-6d74-4a99-9980-3d9212b3bc7b" # Omega19
  - "ab504f4f-82a5-4129-809a-58aececcd328" # bierdosenhalter
  - "8aeaa92e-6a9f-400a-94d5-22b31c96f0d5" # 0Bot
